### ISSUE TITLE
Support for PyG later than 2.0.2

### ISSUE THREAD

**Issue by HaniItani** [vijaydwivedi75/lrgb#6]
Hello,

Any plans for supporting later releases of PyG (e.g. 2.1)? It's a fairly new benchmark and it's not compatible with the newest PyG releases.

Best regards,
Hani

**Comment by rampasek** [comment]
Hi,

You can also access it in GraphGPS that has been updated to PyG 2.0.4 compatibility:
https://github.com/rampasek/GraphGPS

I will refactor GraphGPS to PyG 2.1 in the future. However the dataset loaders themselves should be perfectly functional in your PyG 2.1 codebase as they are.

Best,
Ladislav

**Comment by GARV-k** [comment]
I am also using PyG >2.1 and in the main.py file, I just imported the OptimConfig and SchedulerConfig from torch_geometric.graphgym.optim. 
it gives a error : 
Traceback (most recent call last):
  File "/home/iplab/garv_iit-bhu/GraphTransformer/lrgb/main.py", line 178, in <module>
    optimizer = create_optimizer(model.parameters(),
  File "/home/iplab/anaconda3/envs/lrgb/lib/python3.9/site-packages/torch_geometric/graphgym/optim.py", line 38, in create_optimizer
    return from_config(func)(params, cfg=cfg)
  File "/home/iplab/anaconda3/envs/lrgb/lib/python3.9/site-packages/torch_geometric/graphgym/config.py", line 578, in wrapper
    raise ValueError(f"'cfg.{arg_name}' undefined")
ValueError: 'cfg.optimizer_config' undefined
